workflows:
  android-release:
    name: Android Release Build
    working_directory: form_app
    environment:
      flutter: stable
      java: 17
    scripts:
      - flutter pub get
      - rm -rf ~/.gradle/caches
      - flutter clean
      - flutter build apk --debug --no-shrink
      - cd android && ./gradlew assembleRelease --no-daemon
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
